site_name: CNIO Bioinformatics Unit documentation
site_url: https://bu_cnio.gitlab.io
theme: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/main.css

nav:
  - Home: index.md
  - Development:
    - 'Development guidelines': dev.md
  - HPC resources:
    - 'Usage': hpc/usage.md
    - 'Administration': hpc/admin.md
  - 'systems administration':
    - 'Set up new workstations': admin/tasks.md
